// Generated by CoffeeScript 1.3.3
var DEventData, Schema, fs, path, schema;

fs = require("fs");

path = require("path");

Schema = require("protobuf").Schema;

DEventData = require("../devent").DEventData;

schema = new Schema(fs.readFileSync(path.join(__dirname, "../../messages/devent_examples.desc")));

exports.PING = 1000;

DEventData.register(exports.PING, schema["devent.examples.Ping"]);
