// Generated by CoffeeScript 1.3.3
var BASE, DEventData, Schema, fs, path, schema;

fs = require("fs");

path = require("path");

Schema = require("protobuf").Schema;

DEventData = require("../devents").DEventData;

schema = new Schema(fs.readFileSync(path.join(__dirname, "../../messages/examples.desc")));

BASE = 1000;

exports.PING = BASE;

exports.PONG = BASE + 1;

exports.FINAL = BASE + 2;

DEventData.register(exports.PING, schema["devents.examples.Ping"]);

DEventData.register(exports.PONG, schema["devents.examples.Pong"]);

DEventData.register(exports.FINAL, schema["devents.examples.Final"]);
