// Generated by CoffeeScript 1.3.3
var settings,
  __hasProp = {}.hasOwnProperty;

settings = {
  DEBUG: true,
  ID: 1,
  config: function(options) {
    var key, value;
    for (key in options) {
      if (!__hasProp.call(options, key)) continue;
      value = options[key];
      settings[key] = value;
    }
    return settings;
  }
};

module.exports = settings;
